name: Selenium Automation Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# গিটহাব পেজেসে রিপোর্ট পুশ করার জন্য এই পারমিশনগুলো অবশ্যই লাগবে
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      # - name: Run Tests
      #   run: mvn test -B
      #   continue-on-error: true

      - name: Generate Allure Report
        run: mvn site -DskipTests
        continue-on-error: true

      - name: Generate Allure Report
        run: mvn allure:report -B
        continue-on-error: true

      # আপনার আগের অলুর রেজাল্ট আর্টিফ্যাক্ট
      - name: Upload Allure Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: target/allure-results

      # আপনার আগের অলুর এইচটিএমএল রিপোর্ট আর্টিফ্যাক্ট
      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-report-html
          path: target/site/allure-maven-plugin

      # আপনার আগের সিওরফায়ার রিপোর্ট আর্টিফ্যাক্ট
      - name: Upload Surefire Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: surefire-report
          path: target/surefire-reports

      # [নতুন স্টেপ]: জেনারেট হওয়া অলুর রিপোর্টটি সরাসরি gh-pages ব্রাঞ্চে পাবলিশ করবে
      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/site/allure-maven-plugin # এই ফোল্ডারের ফাইলগুলোই লাইভ ওয়েবসাইট হবে
